name: on-pull-request
run-name: check pull request build

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch contents
        uses: actions/checkout@v4

      - name: Install Ruby packages
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Build site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build
